### ISSUE TITLE
feature request: Add support for Winget installation

### ISSUE THREAD

**Issue by PedromfRibeiro** [appium/appium-inspector#1274]
### Current Behavior

No package found on Winget, to automate processes and simplify things.
Is it possible to add the appium inspector to the Winget repository?

### Suggested Solution

```
PackageIdentifier: Appium.AppiumInspector
PackageVersion: 2023.12.2
Platform:
- Windows.Desktop
InstallerType: nullsoft
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ReleaseDate: 2023-12-02
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/appium/appium-inspector/releases/download/v2023.12.2/Appium-Inspector-windows-2023.12.2-x64.exe
  InstallerSha256: ??
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/appium/appium-inspector/releases/download/v2023.12.2/Appium-Inspector-windows-2023.12.2.exe
  InstallerSha256: ??
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: ??
```
